# JWT CONFIGURATION
application:
    jwt:
        tokenPrefix: Bearer
        secretKey: ${SECRET_KEY}
        tokenExpirationAfterDays: ${EXPIRATION_DAYS}

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ${JDBC_DATABASE_URL}
        username: ${JDBC_DATABASE_USERNAME}
        password: ${JDBC_DATABASE_PASSWORD}
    jpa:
      hibernate:
        ddl-auto: none
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          globally_quoted_identifiers: true
          default_schema: ${DATABASE_SCHEMA}
          dialect: org.hibernate.dialect.PostgreSQLDialect
          
logging:
  file:
    path: /
    name: log.log
  level:
    com: 
      lsoftware:
        inventory: info        
